openapi: '3.0.2'
info:
  title: POKEDEX
  version: '1.0.0'
  description: 'Pokedex service'
servers:
  - url: http://{host}
    description: '"qa" server'
    variables:
      host:
        default: localhost:5000
paths:
  /pokemon/{pokemonName}:
    get:
      description: get pokemon by pokemon name
      tags:
        - pokemon
      parameters:
        - name: pokemonName
          in: path
          description: pokemon name to find
          required: true
          schema:
            type: string
      responses:
        400:
          description: 'Bad Request'
        404:
          description: 'Not Found'
        501:
          description: 'Internal Server Error'
        503:
          description: 'Service Unavailable'
        200:
          description: get pokemon info
          content:
            application/json:
              example:
                {
                  'id': 4,
                  'name': 'charmander',
                  'base_experience': 62,
                  'height': 6,
                  'is_default': true,
                  'order': 5,
                  'weight': 85,
                  'abilities':
                    [
                      {
                        'ability':
                          {
                            'name': 'blaze',
                            'url': 'https://pokeapi.co/api/v2/ability/66/',
                          },
                        'is_hidden': false,
                        'slot': 1,
                      },
                      {
                        'ability':
                          {
                            'name': 'solar-power',
                            'url': 'https://pokeapi.co/api/v2/ability/94/',
                          },
                        'is_hidden': true,
                        'slot': 3,
                      },
                    ],
                  'forms':
                    [
                      {
                        'name': 'charmander',
                        'url': 'https://pokeapi.co/api/v2/pokemon-form/4/',
                      },
                    ],
                  'game_indices':
                    [
                      {
                        'game_index': 176,
                        'version':
                          {
                            'name': 'red',
                            'url': 'https://pokeapi.co/api/v2/version/1/',
                          },
                      },
                    ],
                  'held_items': [],
                  'location_area_encounters': 'https://pokeapi.co/api/v2/pokemon/4/encounters',
                  'moves':
                    [
                      {
                        'move':
                          {
                            'name': 'mega-punch',
                            'url': 'https://pokeapi.co/api/v2/move/5/',
                          },
                        'version_group_details':
                          [
                            {
                              'level_learned_at': 0,
                              'move_learn_method':
                                {
                                  'name': 'machine',
                                  'url': 'https://pokeapi.co/api/v2/move-learn-method/4/',
                                },
                              'version_group':
                                {
                                  'name': 'red-blue',
                                  'url': 'https://pokeapi.co/api/v2/version-group/1/',
                                },
                            },
                            {
                              'level_learned_at': 0,
                              'move_learn_method':
                                {
                                  'name': 'machine',
                                  'url': 'https://pokeapi.co/api/v2/move-learn-method/4/',
                                },
                              'version_group':
                                {
                                  'name': 'yellow',
                                  'url': 'https://pokeapi.co/api/v2/version-group/2/',
                                },
                            },
                            {
                              'level_learned_at': 0,
                              'move_learn_method':
                                {
                                  'name': 'tutor',
                                  'url': 'https://pokeapi.co/api/v2/move-learn-method/3/',
                                },
                              'version_group':
                                {
                                  'name': 'emerald',
                                  'url': 'https://pokeapi.co/api/v2/version-group/6/',
                                },
                            },
                            {
                              'level_learned_at': 0,
                              'move_learn_method':
                                {
                                  'name': 'tutor',
                                  'url': 'https://pokeapi.co/api/v2/move-learn-method/3/',
                                },
                              'version_group':
                                {
                                  'name': 'firered-leafgreen',
                                  'url': 'https://pokeapi.co/api/v2/version-group/7/',
                                },
                            },
                            {
                              'level_learned_at': 0,
                              'move_learn_method':
                                {
                                  'name': 'machine',
                                  'url': 'https://pokeapi.co/api/v2/move-learn-method/4/',
                                },
                              'version_group':
                                {
                                  'name': 'sword-shield',
                                  'url': 'https://pokeapi.co/api/v2/version-group/20/',
                                },
                            },
                          ],
                      },
                    ],
                  'past_types': [],
                  'sprites':
                    {
                      'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/4.png',
                      'back_female': null,
                      'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/4.png',
                      'back_shiny_female': null,
                      'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
                      'front_female': null,
                      'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/4.png',
                      'front_shiny_female': null,
                      'other':
                        {
                          'dream_world':
                            {
                              'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/4.svg',
                              'front_female': null,
                            },
                          'home':
                            {
                              'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/4.png',
                              'front_female': null,
                              'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/shiny/4.png',
                              'front_shiny_female': null,
                            },
                          'official-artwork':
                            {
                              'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png',
                            },
                        },
                      'versions':
                        {
                          'generation-i':
                            {
                              'red-blue':
                                {
                                  'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/back/4.png',
                                  'back_gray': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/back/gray/4.png',
                                  'back_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/back/4.png',
                                  'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/4.png',
                                  'front_gray': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/gray/4.png',
                                  'front_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/4.png',
                                },
                              'yellow':
                                {
                                  'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/back/4.png',
                                  'back_gray': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/back/gray/4.png',
                                  'back_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/transparent/back/4.png',
                                  'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/4.png',
                                  'front_gray': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/gray/4.png',
                                  'front_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/transparent/4.png',
                                },
                            },
                        },
                    },
                  'species':
                    {
                      'name': 'charmander',
                      'url': 'https://pokeapi.co/api/v2/pokemon-species/4/',
                    },
                  'stats':
                    [
                      {
                        'base_stat': 39,
                        'effort': 0,
                        'stat':
                          {
                            'name': 'hp',
                            'url': 'https://pokeapi.co/api/v2/stat/1/',
                          },
                      },
                    ],
                  'types':
                    [
                      {
                        'slot': 1,
                        'type':
                          {
                            'name': 'fire',
                            'url': 'https://pokeapi.co/api/v2/type/10/',
                          },
                      },
                    ],
                }
components:
  schemas:
    Pokemon:
      properties:
        id:
          type: number
        name:
          type: string
        base_experience:
          type: number
        height:
          type: number
        is_default:
          type: boolean
        order:
          type: number
        weight:
          type: number
        abilities:
          type: array
          items:
            $ref: '#/components/schemas/PokemonAbility'
        forms:
          type: object
        game_indices:
          type: array
          items:
            $ref: '#/components/schemas/VersionGameIndex'
        held_items:
          type: array
          items:
            $ref: '#/components/schemas/PokemonHeldItem'
        location_area_encounters:
          type: string
        moves:
          type: array
          items:
            $ref: '#/components/schemas/PokemonMove'
        past_types:
          type: array
          items:
            $ref: '#/components/schemas/PokemonTypePast'
        sprites:
          type: object
        species:
          type: object
        stats:
          type: array
          items:
            $ref: '#/components/schemas/PokemonStat'
        types:
          type: array
          items:
            $ref: '#/components/schemas/PokemonType'
    NamedAPIResource:
      properties:
        name:
          type: string
        url:
          type: string
    PokemonAbility:
      properties:
        is_hidden:
          type: boolean
        slot:
          type: number
        ability:
          type: object
    VersionGameIndex:
      properties:
        game_index:
          type: number
        version:
          type: object
    PokemonHeldItem:
      properties:
        item:
          type: object
        version_details:
          type: object
    PokemonMove:
      properties:
        move:
          type: object
        version_group_details:
          type: array
          items:
            $ref: '#/components/schemas/PokemonMoveVersion'
    PokemonTypePast:
      properties:
        generation:
          type: object
        types:
          type: array
          items:
            $ref: '#/components/schemas/PokemonType'
    PokemonSprites:
      properties:
        front_default:
          type: string
        front_shiny:
          type: string
        front_female:
          type: string
        front_shiny_female:
          type: string
        back_default:
          type: string
        back_shiny:
          type: string
        back_female:
          type: string
        back_shiny_female:
          type: string
    PokemonStat:
      properties:
        stat:
          type: object
        effort:
          type: number
        base_stat:
          type: number
    PokemonType:
      properties:
        slot:
          type: number
        type:
          type: object
    PokemonMoveVersion:
      properties:
        level_learned_at:
          type: number
